### ISSUE TITLE
multipart component

### ISSUE THREAD

**Issue by steel-ne** [qeda/qeda#20]
I want to split 144-pin component to separate domains, because all 144-pin IC symbol does not fit on page.
For example stm32f429z.
I want split it to 3 parts: POWER (vcc+vss), LTDC,  GPIO
problem with domain GPIO - how can I select pins, that does not included in LTDC?

**Comment by steel-ne** [comment]
[stm32f429z.yaml.zip](https://github.com/qeda/qeda/files/536124/stm32f429z.yaml.zip)
part GPIO include all pins. How to exclude LTDC?

**Comment by shamil-ru** [comment]
You are to manually exclude these `LTDC` pins from `PORTA` ... `PORTH` groups.
