### ISSUE TITLE
3d models

### ISSUE THREAD

**Issue by Gasman2014** [qeda/qeda#23]
No 3d models being generated yet. Is this still in the planning stage?

**Comment by shamil-ru** [comment]
There is experimental 3D support added recently (not included to release yet). Not realistic models but body boxes.
![3d](https://cloud.githubusercontent.com/assets/4997723/23295429/a81d49a0-fa81-11e6-90c4-597c4034136e.png)

**Comment by tiborgats** [comment]
If it would have body cylinders also, it will be already very useful for checking mechanical designs.

**Comment by Gasman2014** [comment]
For mechanical models, a STEP model would be preferable. I think the present output is .wrl.

**Comment by tiborgats** [comment]
True, `.STEP` is more universal, and already handled by the nightly version of KiCad. If it helps the development of QEDA, some nice `.STEP` examples can be generated by the evaluation version of [PCB Library Expert](http://www.pcblibraries.com/Products/FPX/KiCad.asp).

**Comment by shamil-ru** [comment]
Looking forward to STEP support to be added to main release of KiCad. But only VRML is supported at the moment.

**Comment by Gasman2014** [comment]
Yes but STEP has been supported directly for some while in the nightly builds

> Note
> UPDATE 2016-09-07 The OCE plugin for STEP and IGES 3D viewer support was merged with the offical development branch recently and should now be available in the newest nightlies.

I don't imagine that it will be too much longer before STEP support reaches the stable release. 4.0.6 has just been released and I have seen some comments on the developer site hinting at a spring release for a 4.5 version and this would include a cherry picked selection of the stuff presently in the nightly builds. The v5 roadmap as recently outlined by Wayne S (https://drive.google.com/file/d/0B8ng6CtJ1Hh6NU11UTRrbzZBYjg/view) certainly plans to include more 3d model support and I am fairly sure that the current OCE STEP support has been considered stable.

**Comment by tiborgats** [comment]
It would be nice to have an option for the footprint: a path to an already existing 3D file. (And if it is given, you don't have to generate a 3D model for that footprint.) Many complicated parts have already existing 3D models downloadable from their manufacturers in STEP file format, I would prefer to use them.

**Comment by m-byte** [comment]
This might be a few years late, but at least for KiCad7, custom models are possible since https://github.com/qeda/qeda/pull/102. If anyone needs support for older versions, of KiCad, please open a new issue. VRML models have also been support for years now, so I'm closing this.
