### ISSUE TITLE
use custom git repo

### ISSUE THREAD

**Issue by steel-ne** [qeda/qeda#4]
Can I use custom git repo for 'qeda load' command? I clone original 'qeda/library' repo, and want to use it.

Symlinking to project's './library' catalog is not good idea - any 'qeda load' command can silently replace files in my working repo

**Comment by shamil-ru** [comment]
You may use `git clone` + `qeda add` instead of `qeda load`. When you run `qeda add` command it primarily searches element in local `library` subdirectory.

``` bash
git clone https://github.com/<your login>/<your repo>.git
mv <your repo> library
qeda add <element>
```

**Comment by steel-ne** [comment]
I must not forget `git pull` every time. Ok, I'l try to live with it )
