### ISSUE TITLE
svg backend

### ISSUE THREAD

**Issue by dvc94ch** [qeda/qeda#44]
A svg backend would be really useful. This would add support for generating schematics using netlistsvg.

[0] https://github.com/nturley/netlistsvg
[1] https://raw.githubusercontent.com/nturley/netlistsvg/master/lib/analog.svg

**Comment by shamil-ru** [comment]
This is a good idea, I was thinking about it.

There is a need to add `custom` symbol generator. And it should support SVG paths.

**Comment by dvc94ch** [comment]
Status update on exporting symbols to svg

- The pin spacing for kicad pins doesn't seem consistent. (resistor pin to rectangle space seems less than transistor-npn pin to circle). I need to find a way to remove it.
- Need to add a way to get the symbol width / height
- Some symbols (nfet and zener) seem to be off (zener additional pad)
- Find a way to add allowed orientations to yaml configuration (horizontal, vertical, horizontal-flipped, vertical-flipped) and allow exporting the symbol in all allowed orientations

![screenshot from 2018-01-28 17-31-45](https://user-images.githubusercontent.com/741807/35484559-d4748bd2-0451-11e8-824f-691779141d8a.png)
