### ISSUE TITLE
symbol FET seems broken

### ISSUE THREAD

**Issue by steel-ne** [qeda/qeda#8]
1. I'm trying library element 'irf/irf4905s.yaml', but symbol is generated without pins

![image](https://cloud.githubusercontent.com/assets/195610/18796594/b00b4c66-81d2-11e6-9350-5f2a78c5e859.png)
1. Can I use FET-symbol in multipart element, such as IRF7313 - dual N-FETs?

PS. qeda version is 0.2.4

**Comment by shamil-ru** [comment]
Thank you for reporting. This bug was introduced quite recently.

Fixed in v0.2.5.

Additionally multi-part capability implemented ([IRF7313](https://github.com/qeda/library/blob/master/irf/irf7313.yaml) has been added to library).
