### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by FastRabbit** [qeda/qeda#9]
Is it possible to change the place for the downloaded Libraries?
I don't like it when the OS /Library folder get populated with all the new folders for the downloaded libraries.
If not make at least a folder /Library/qeda/ where you put all  the downloaded stuff.

Thanks in advance

**Comment by shamil-ru** [comment]
It is not obligatory to work in root directory. You may run `qeda` command in any directory and `library` subdirectory will be created relatively to current directory. If you run `qeda` command in `/home/user/project/` directory then component descriptions will be cached to `/home/user/project/library/`.
